name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...
      
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.14'
    - name: Run coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)

  

